### ISSUE TITLE
Could not find a valid gem

### ISSUE THREAD

**Issue by manishrc** [promohunt/promostandards-client#2]
Running the following command: 
`gem install promostandards-client -s https://github.com/promohunt/promostandards-client`

Gives me the following error:
```
ERROR:  Could not find a valid gem 'promostandards-client' (>= 0), here is why:
          Unable to download data from https://github.com/promohunt/promostandards-client/ - bad response Not Found 404 (https://github.com/promohunt/promostandards-client/specs.4.8.gz)
ERROR:  Possible alternatives: mustard_client, prometheus-client, boost-jaeger-client, cassandra_client, drools_lambda_client
```

I'm using ruby 2.5.1p57

**Comment by akshaysmurthy** [comment]
You cannot install gems from Github via the command line without bundler. The `-s` option expects to find a gem server.

Thanks for pointing out. I will remove this in the README for now.
